apiVersion: apps/v1
kind: Deployment
metadata:
  name: itaap-poc-ms-utility-deployment
  namespace: {{deployNamespace}}
  labels:
    app: itaap-poc-ms-utility
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itaap-poc-ms-utility
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: itaap-poc-ms-utility
    spec:
      containers:
        - name: itaap-poc-ms-utility-container
          image: >-
            762168133611.dkr.ecr.eu-west-1.amazonaws.com/itaap/poc/itaap-poc-ms-utility:{{imageTagName}}

          ports:
            - containerPort: 8085
              protocol: TCP     
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: APP_VERSION
              value: {{appVersion}}
            - name: APP_ENV
              value: {{appEnv}}
            - name: AUDIT_CONNECTOR_URL
              valueFrom:
                configMapKeyRef:
                  name: audit-connector-data
                  key: AUDIT_CONNECTOR_URL
            - name: AUDIT_CONNECTOR_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: audit-connector-data
                  key: AUDIT_CONNECTOR_USERNAME
            - name: AUDIT_CONNECTOR_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: audit-connector-data
                  key: AUDIT_CONNECTOR_PASSWORD  
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          resources:
           requests:
             memory: "256Mi"
             cpu: "25m" 
           limits:
             memory: "512Mi"
             cpu: "100m"  
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64                        
      restartPolicy: Always
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600


---

apiVersion: v1
kind: Service
metadata:
  name: itaap-poc-ms-utility-service
  namespace: {{deployNamespace}}
  labels:
    app: itaap-poc-ms-utility
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: itaap-poc-ms-utility











