CREATE TABLE POC.ACC_PROD (
  ID SERIAL NOT NULL,
  STAGE INTEGER,
  BUILD_NUMBER VARCHAR,
  STATE VARCHAR,
  DEPLOYMENT_DATE TIMESTAMP,
  DOCUMENTS INTEGER,
  DEPLOYMENT_ID INTEGER NOT NULL,
  BUILD_ID INTEGER,
CONSTRAINT ACC_PROD_PK PRIMARY KEY (ID)
);

CREATE TABLE POC.DEPLOYMENT (
  ID INTEGER NOT NULL,
  DEPLOYMENT_DEV INTEGER,
  DEPLOYMENT_TEST INTEGER,
  TGL TIMESTAMP,
  BGL TIMESTAMP,
  MICROSERVICE_ID INTEGER,
  POSTMAN_COLLECTION INT4 NULL,
  ITD INT4 NULL,
CONSTRAINT DEPLOYMENT_PK PRIMARY KEY (ID)
);

CREATE TABLE POC.DOCUMENTS (
  ID SERIAL NOT NULL,
  IQ INT4 NULL,
  PIQ INT4 NULL,
  SIGN_OFF_KT TIMESTAMP,
  SIGN_OFF_SIT TIMESTAMP,
  SIGN_OFF_UAT TIMESTAMP,
  SIGN_OFF_PT TIMESTAMP,
  SIGN_OFF_ST TIMESTAMP,
  AZURE_VARIABLES INT4 NULL,
CONSTRAINT DOCUMENTS_PK PRIMARY KEY (ID)
);

CREATE TABLE POC.MICROSERVICES (
  MICROSERVICE_ID INTEGER NOT NULL,
  NAME VARCHAR,
  TARGET_COMPLETION_DATE TIMESTAMP,
  TECH_LEAD_ID INTEGER NOT NULL,
  DEVELOPER_ID INTEGER NOT NULL,
  BACKUP_ID INTEGER NOT NULL,
  SCRUM_MASTER_ID INTEGER NOT NULL,
  POC_ID INTEGER NOT NULL,
  DEPLOYMENT_ID INTEGER,
  STATUS VARCHAR,
  PIPELINE_ID INTEGER NOT NULL,
CONSTRAINT MICROSERVICES_PK PRIMARY KEY (MICROSERVICE_ID)
);

CREATE TABLE POC.NON_PROD (
  ID SERIAL NOT NULL,
  STAGE INTEGER,
  BUILD_NUMBER VARCHAR,
  DEPLOYMENT_DATE TIMESTAMP,
  STATE VARCHAR,
  BUILD_ID INTEGER,
  MICROSERVICE_ID INTEGER NOT NULL,
CONSTRAINT NON_PROD_PK PRIMARY KEY (ID)
);

CREATE TABLE POC.TASKS (
  ID INTEGER NOT NULL,
  TASK_DESCRIPTION TEXT,
  TASK_TITLE VARCHAR,
  PRIORITY VARCHAR(1),
  STATUS VARCHAR(1),
  MICROSERVICE_ID INTEGER NOT NULL,
  CREATED_BY INTEGER NOT NULL,
  START_DATE TIMESTAMP,
  DUE_DATE TIMESTAMP,
  CREATED_DATE TIMESTAMP,
  MODIFIED_DATE TIMESTAMP,
  COMPLETED_DATE TIMESTAMP,
  COMPLETION_COMMENTS VARCHAR,
  NOTES TEXT,
  IMPEDIMENTS TEXT,
CONSTRAINT TASKS_PK PRIMARY KEY (ID)
);

CREATE TABLE POC.USERS (
  ID INTEGER NOT NULL,
  NAME VARCHAR,
  EMAIL VARCHAR,
  ROLE VARCHAR(1),
  AVATAR INT4 NULL,
  JOINING_DATE TIMESTAMP NULL,
  DESIGNATION VARCHAR(255) NULL,
CONSTRAINT USERS_PK PRIMARY KEY (ID)
);

CREATE TABLE POC.FILES (
  ID SERIAL NOT NULL,
  FILE_NAME VARCHAR(1000),
  FILE_EXTENSION VARCHAR(50),
  DATA TEXT,
CONSTRAINT FILES_PK PRIMARY KEY (ID)
);

CREATE TABLE POC.TASKLIST (
  ID SERIAL NOT NULL,
  TASK_ID INT4 NOT NULL,
  TASK_DETAILS TEXT,
  ADDED_ON TIMESTAMP,
  COMPLETED_ON TIMESTAMP,
  COMPLETED_BY INT4,
  COMPLETED BOOLEAN,
CONSTRAINT TASKLIST_PK PRIMARY KEY (ID)
);

CREATE TABLE POC.ATTACHMENTS_TASK_FILES (
  TASK_ID INT4 NOT NULL,
  FILES_ID INT4 NOT NULL
);

CREATE TABLE POC.USERS_ASSIGNED_TASKS (
  ID SERIAL NOT NULL,
  TASK_ID INT4 NOT NULL,
  USER_ID INT4 NOT NULL,
  ACCEPTED BOOLEAN DEFAULT FALSE,
  CONSTRAINT USER_TASKS_PK PRIMARY KEY (ID)
);

CREATE TABLE POC.COMMENTS (
  ID SERIAL NOT NULL,
  TASK_ID INT4 NOT NULL,
  GIVEN_BY_USER_ID INT4 NULL,
  COMMENTS TEXT NULL,
  TIMESTAMP TIMESTAMP NULL,
CONSTRAINT COMMENTS_PK PRIMARY KEY (ID)
);

ALTER TABLE POC.ACC_PROD ADD CONSTRAINT ACC_PROD_FK0 FOREIGN KEY (DOCUMENTS) REFERENCES POC.DOCUMENTS(ID);

ALTER TABLE POC.DEPLOYMENT ADD CONSTRAINT DEPLOYMENT_FK0 FOREIGN KEY (DEPLOYMENT_DEV) REFERENCES POC.NON_PROD(ID);
ALTER TABLE POC.DEPLOYMENT ADD CONSTRAINT DEPLOYMENT_FK1 FOREIGN KEY (DEPLOYMENT_TEST) REFERENCES POC.NON_PROD(ID);
ALTER TABLE POC.DEPLOYMENT ADD CONSTRAINT DEPLOYMENT_FK2 FOREIGN KEY (POSTMAN_COLLECTION) REFERENCES POC.FILES(ID);
ALTER TABLE POC.DEPLOYMENT ADD CONSTRAINT DEPLOYMENT_FK3 FOREIGN KEY (ITD) REFERENCES POC.FILES(ID);

ALTER TABLE POC.DOCUMENTS ADD CONSTRAINT DOCUMENTS_FK0 FOREIGN KEY (IQ) REFERENCES POC.FILES(ID);
ALTER TABLE POC.DOCUMENTS ADD CONSTRAINT DOCUMENTS_FK1 FOREIGN KEY (PIQ) REFERENCES POC.FILES(ID);
ALTER TABLE POC.DOCUMENTS ADD CONSTRAINT DOCUMENTS_FK2 FOREIGN KEY (AZURE_VARIABLES) REFERENCES POC.FILES(ID);

ALTER TABLE POC.MICROSERVICES ADD CONSTRAINT MICROSERVICES_FK0 FOREIGN KEY (TECH_LEAD_ID) REFERENCES POC.USERS(ID);
ALTER TABLE POC.MICROSERVICES ADD CONSTRAINT MICROSERVICES_FK1 FOREIGN KEY (DEVELOPER_ID) REFERENCES POC.USERS(ID);
ALTER TABLE POC.MICROSERVICES ADD CONSTRAINT MICROSERVICES_FK2 FOREIGN KEY (BACKUP_ID) REFERENCES POC.USERS(ID);
ALTER TABLE POC.MICROSERVICES ADD CONSTRAINT MICROSERVICES_FK3 FOREIGN KEY (SCRUM_MASTER_ID) REFERENCES POC.USERS(ID);
ALTER TABLE POC.MICROSERVICES ADD CONSTRAINT MICROSERVICES_FK4 FOREIGN KEY (POC_ID) REFERENCES POC.USERS(ID);
ALTER TABLE POC.MICROSERVICES ADD CONSTRAINT MICROSERVICES_FK5 FOREIGN KEY (DEPLOYMENT_ID) REFERENCES POC.DEPLOYMENT(ID);

ALTER TABLE POC.TASKS ADD CONSTRAINT TASKS_FK0 FOREIGN KEY (MICROSERVICE_ID) REFERENCES POC.MICROSERVICES(MICROSERVICE_ID);
ALTER TABLE POC.TASKS ADD CONSTRAINT TASKS_FK1 FOREIGN KEY (CREATED_BY) REFERENCES POC.USERS(ID);

ALTER TABLE POC.USERS ADD CONSTRAINT USERS_FK0 FOREIGN KEY (AVATAR) REFERENCES POC.FILES(ID);

ALTER TABLE POC.ATTACHMENTS_TASK_FILES ADD CONSTRAINT ATTACHMENTS_TASK_FILES_FK0 FOREIGN KEY (TASK_ID) REFERENCES POC.TASKS(ID);
ALTER TABLE POC.ATTACHMENTS_TASK_FILES ADD CONSTRAINT ATTACHMENTS_TASK_FILES_FK1 FOREIGN KEY (FILES_ID) REFERENCES POC.FILES(ID);

ALTER TABLE POC.USERS_ASSIGNED_TASKS ADD CONSTRAINT USERS_ASSIGNED_TASKS_FK0 FOREIGN KEY (TASK_ID) REFERENCES POC.TASKS(ID);
ALTER TABLE POC.USERS_ASSIGNED_TASKS ADD CONSTRAINT USERS_ASSIGNED_TASKS_FK1 FOREIGN KEY (USER_ID) REFERENCES POC.USERS(ID);